// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Love.proto

package com.story.netty.protobufDemo2;

public final class MyDataInfo {
  private MyDataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ManagerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Manager)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 枚举类在当前message中的编号
     * </pre>
     *
     * <code>.Manager.DataType data_type = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <pre>
     * 枚举类在当前message中的编号
     * </pre>
     *
     * <code>.Manager.DataType data_type = 1;</code>
     */
    Manager.DataType getDataType();

    /**
     * <code>.Love love = 2;</code>
     */
    boolean hasLove();
    /**
     * <code>.Love love = 2;</code>
     */
    Love getLove();
    /**
     * <code>.Love love = 2;</code>
     */
    LoveOrBuilder getLoveOrBuilder();

    /**
     * <code>.Hurt hurt = 3;</code>
     */
    boolean hasHurt();
    /**
     * <code>.Hurt hurt = 3;</code>
     */
    Hurt getHurt();
    /**
     * <code>.Hurt hurt = 3;</code>
     */
    HurtOrBuilder getHurtOrBuilder();

    public Manager.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   * 用一个message管理其他message
   * </pre>
   *
   * Protobuf type {@code Manager}
   */
  public  static final class Manager extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Manager)
      ManagerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Manager.newBuilder() to construct.
    private Manager(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Manager() {
      dataType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Manager(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              Love.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((Love) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(Love.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Love) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              Hurt.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((Hurt) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(Hurt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Hurt) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_Manager_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_Manager_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Manager.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Manager.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LoveType = 0;</code>
       */
      LoveType(0),
      /**
       * <code>HurtType = 1;</code>
       */
      HurtType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LoveType = 0;</code>
       */
      public static final int LoveType_VALUE = 0;
      /**
       * <code>HurtType = 1;</code>
       */
      public static final int HurtType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return LoveType;
          case 1: return HurtType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Manager.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Manager.DataType)
    }

    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      LOVE(2),
      HURT(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return LOVE;
          case 3: return HURT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     * 枚举类在当前message中的编号
     * </pre>
     *
     * <code>.Manager.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     * 枚举类在当前message中的编号
     * </pre>
     *
     * <code>.Manager.DataType data_type = 1;</code>
     */
    public DataType getDataType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int LOVE_FIELD_NUMBER = 2;
    /**
     * <code>.Love love = 2;</code>
     */
    public boolean hasLove() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Love love = 2;</code>
     */
    public Love getLove() {
      if (dataBodyCase_ == 2) {
         return (Love) dataBody_;
      }
      return Love.getDefaultInstance();
    }
    /**
     * <code>.Love love = 2;</code>
     */
    public LoveOrBuilder getLoveOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (Love) dataBody_;
      }
      return Love.getDefaultInstance();
    }

    public static final int HURT_FIELD_NUMBER = 3;
    /**
     * <code>.Hurt hurt = 3;</code>
     */
    public boolean hasHurt() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Hurt hurt = 3;</code>
     */
    public Hurt getHurt() {
      if (dataBodyCase_ == 3) {
         return (Hurt) dataBody_;
      }
      return Hurt.getDefaultInstance();
    }
    /**
     * <code>.Hurt hurt = 3;</code>
     */
    public HurtOrBuilder getHurtOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (Hurt) dataBody_;
      }
      return Hurt.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != DataType.LoveType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (Love) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (Hurt) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != DataType.LoveType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Love) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Hurt) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Manager)) {
        return super.equals(obj);
      }
      Manager other = (Manager) obj;

      boolean result = true;
      result = result && dataType_ == other.dataType_;
      result = result && getDataBodyCase().equals(
          other.getDataBodyCase());
      if (!result) return false;
      switch (dataBodyCase_) {
        case 2:
          result = result && getLove()
              .equals(other.getLove());
          break;
        case 3:
          result = result && getHurt()
              .equals(other.getHurt());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + LOVE_FIELD_NUMBER;
          hash = (53 * hash) + getLove().hashCode();
          break;
        case 3:
          hash = (37 * hash) + HURT_FIELD_NUMBER;
          hash = (53 * hash) + getHurt().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Manager parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Manager parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Manager parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Manager parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Manager parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Manager parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Manager parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Manager parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Manager parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Manager parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Manager parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Manager parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Manager prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用一个message管理其他message
     * </pre>
     *
     * Protobuf type {@code Manager}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Manager)
        ManagerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_Manager_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_Manager_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Manager.class, Builder.class);
      }

      // Construct using com.story.netty.protobufDemo2.MyDataInfo.Manager.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_Manager_descriptor;
      }

      @Override
      public Manager getDefaultInstanceForType() {
        return Manager.getDefaultInstance();
      }

      @Override
      public Manager build() {
        Manager result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Manager buildPartial() {
        Manager result = new Manager(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (loveBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = loveBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (hurtBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = hurtBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Manager) {
          return mergeFrom((Manager)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Manager other) {
        if (other == Manager.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case LOVE: {
            mergeLove(other.getLove());
            break;
          }
          case HURT: {
            mergeHurt(other.getHurt());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Manager parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Manager) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       * 枚举类在当前message中的编号
       * </pre>
       *
       * <code>.Manager.DataType data_type = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       * 枚举类在当前message中的编号
       * </pre>
       *
       * <code>.Manager.DataType data_type = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 枚举类在当前message中的编号
       * </pre>
       *
       * <code>.Manager.DataType data_type = 1;</code>
       */
      public DataType getDataType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 枚举类在当前message中的编号
       * </pre>
       *
       * <code>.Manager.DataType data_type = 1;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 枚举类在当前message中的编号
       * </pre>
       *
       * <code>.Manager.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Love, Love.Builder, LoveOrBuilder> loveBuilder_;
      /**
       * <code>.Love love = 2;</code>
       */
      public boolean hasLove() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public Love getLove() {
        if (loveBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (Love) dataBody_;
          }
          return Love.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return loveBuilder_.getMessage();
          }
          return Love.getDefaultInstance();
        }
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public Builder setLove(Love value) {
        if (loveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          loveBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public Builder setLove(
          Love.Builder builderForValue) {
        if (loveBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          loveBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public Builder mergeLove(Love value) {
        if (loveBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != Love.getDefaultInstance()) {
            dataBody_ = Love.newBuilder((Love) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            loveBuilder_.mergeFrom(value);
          }
          loveBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public Builder clearLove() {
        if (loveBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          loveBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public Love.Builder getLoveBuilder() {
        return getLoveFieldBuilder().getBuilder();
      }
      /**
       * <code>.Love love = 2;</code>
       */
      public LoveOrBuilder getLoveOrBuilder() {
        if ((dataBodyCase_ == 2) && (loveBuilder_ != null)) {
          return loveBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (Love) dataBody_;
          }
          return Love.getDefaultInstance();
        }
      }
      /**
       * <code>.Love love = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Love, Love.Builder, LoveOrBuilder>
          getLoveFieldBuilder() {
        if (loveBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = Love.getDefaultInstance();
          }
          loveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Love, Love.Builder, LoveOrBuilder>(
                  (Love) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return loveBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Hurt, Hurt.Builder, HurtOrBuilder> hurtBuilder_;
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public boolean hasHurt() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public Hurt getHurt() {
        if (hurtBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (Hurt) dataBody_;
          }
          return Hurt.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return hurtBuilder_.getMessage();
          }
          return Hurt.getDefaultInstance();
        }
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public Builder setHurt(Hurt value) {
        if (hurtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          hurtBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public Builder setHurt(
          Hurt.Builder builderForValue) {
        if (hurtBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          hurtBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public Builder mergeHurt(Hurt value) {
        if (hurtBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != Hurt.getDefaultInstance()) {
            dataBody_ = Hurt.newBuilder((Hurt) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            hurtBuilder_.mergeFrom(value);
          }
          hurtBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public Builder clearHurt() {
        if (hurtBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          hurtBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public Hurt.Builder getHurtBuilder() {
        return getHurtFieldBuilder().getBuilder();
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      public HurtOrBuilder getHurtOrBuilder() {
        if ((dataBodyCase_ == 3) && (hurtBuilder_ != null)) {
          return hurtBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (Hurt) dataBody_;
          }
          return Hurt.getDefaultInstance();
        }
      }
      /**
       * <code>.Hurt hurt = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Hurt, Hurt.Builder, HurtOrBuilder>
          getHurtFieldBuilder() {
        if (hurtBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = Hurt.getDefaultInstance();
          }
          hurtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Hurt, Hurt.Builder, HurtOrBuilder>(
                  (Hurt) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return hurtBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Manager)
    }

    // @@protoc_insertion_point(class_scope:Manager)
    private static final Manager DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Manager();
    }

    public static Manager getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Manager>
        PARSER = new com.google.protobuf.AbstractParser<Manager>() {
      @Override
      public Manager parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Manager(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Manager> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Manager> getParserForType() {
      return PARSER;
    }

    @Override
    public Manager getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Love)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 loveTimes = 1;</code>
     */
    int getLoveTimes();

    /**
     * <code>string loveName = 2;</code>
     */
    String getLoveName();
    /**
     * <code>string loveName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoveNameBytes();
  }
  /**
   * Protobuf type {@code Love}
   */
  public  static final class Love extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Love)
      LoveOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Love.newBuilder() to construct.
    private Love(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Love() {
      loveTimes_ = 0;
      loveName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Love(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              loveTimes_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              loveName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_Love_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_Love_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Love.class, Builder.class);
    }

    public static final int LOVETIMES_FIELD_NUMBER = 1;
    private int loveTimes_;
    /**
     * <code>int32 loveTimes = 1;</code>
     */
    public int getLoveTimes() {
      return loveTimes_;
    }

    public static final int LOVENAME_FIELD_NUMBER = 2;
    private volatile Object loveName_;
    /**
     * <code>string loveName = 2;</code>
     */
    public String getLoveName() {
      Object ref = loveName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        loveName_ = s;
        return s;
      }
    }
    /**
     * <code>string loveName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoveNameBytes() {
      Object ref = loveName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        loveName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (loveTimes_ != 0) {
        output.writeInt32(1, loveTimes_);
      }
      if (!getLoveNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loveName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (loveTimes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, loveTimes_);
      }
      if (!getLoveNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loveName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Love)) {
        return super.equals(obj);
      }
      Love other = (Love) obj;

      boolean result = true;
      result = result && (getLoveTimes()
          == other.getLoveTimes());
      result = result && getLoveName()
          .equals(other.getLoveName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOVETIMES_FIELD_NUMBER;
      hash = (53 * hash) + getLoveTimes();
      hash = (37 * hash) + LOVENAME_FIELD_NUMBER;
      hash = (53 * hash) + getLoveName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Love parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Love parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Love parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Love parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Love parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Love parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Love parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Love parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Love parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Love parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Love parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Love parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Love prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Love}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Love)
        LoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_Love_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_Love_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Love.class, Builder.class);
      }

      // Construct using com.story.netty.protobufDemo2.MyDataInfo.Love.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        loveTimes_ = 0;

        loveName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_Love_descriptor;
      }

      @Override
      public Love getDefaultInstanceForType() {
        return Love.getDefaultInstance();
      }

      @Override
      public Love build() {
        Love result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Love buildPartial() {
        Love result = new Love(this);
        result.loveTimes_ = loveTimes_;
        result.loveName_ = loveName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Love) {
          return mergeFrom((Love)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Love other) {
        if (other == Love.getDefaultInstance()) return this;
        if (other.getLoveTimes() != 0) {
          setLoveTimes(other.getLoveTimes());
        }
        if (!other.getLoveName().isEmpty()) {
          loveName_ = other.loveName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Love parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Love) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int loveTimes_ ;
      /**
       * <code>int32 loveTimes = 1;</code>
       */
      public int getLoveTimes() {
        return loveTimes_;
      }
      /**
       * <code>int32 loveTimes = 1;</code>
       */
      public Builder setLoveTimes(int value) {
        
        loveTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 loveTimes = 1;</code>
       */
      public Builder clearLoveTimes() {
        
        loveTimes_ = 0;
        onChanged();
        return this;
      }

      private Object loveName_ = "";
      /**
       * <code>string loveName = 2;</code>
       */
      public String getLoveName() {
        Object ref = loveName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          loveName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string loveName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoveNameBytes() {
        Object ref = loveName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          loveName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loveName = 2;</code>
       */
      public Builder setLoveName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loveName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loveName = 2;</code>
       */
      public Builder clearLoveName() {
        
        loveName_ = getDefaultInstance().getLoveName();
        onChanged();
        return this;
      }
      /**
       * <code>string loveName = 2;</code>
       */
      public Builder setLoveNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loveName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Love)
    }

    // @@protoc_insertion_point(class_scope:Love)
    private static final Love DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Love();
    }

    public static Love getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Love>
        PARSER = new com.google.protobuf.AbstractParser<Love>() {
      @Override
      public Love parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Love(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Love> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Love> getParserForType() {
      return PARSER;
    }

    @Override
    public Love getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HurtOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Hurt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 hurtTimes = 1;</code>
     */
    int getHurtTimes();

    /**
     * <code>string hurtName = 2;</code>
     */
    String getHurtName();
    /**
     * <code>string hurtName = 2;</code>
     */
    com.google.protobuf.ByteString
        getHurtNameBytes();
  }
  /**
   * Protobuf type {@code Hurt}
   */
  public  static final class Hurt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Hurt)
      HurtOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hurt.newBuilder() to construct.
    private Hurt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hurt() {
      hurtTimes_ = 0;
      hurtName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hurt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              hurtTimes_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              hurtName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyDataInfo.internal_static_Hurt_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyDataInfo.internal_static_Hurt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Hurt.class, Builder.class);
    }

    public static final int HURTTIMES_FIELD_NUMBER = 1;
    private int hurtTimes_;
    /**
     * <code>int32 hurtTimes = 1;</code>
     */
    public int getHurtTimes() {
      return hurtTimes_;
    }

    public static final int HURTNAME_FIELD_NUMBER = 2;
    private volatile Object hurtName_;
    /**
     * <code>string hurtName = 2;</code>
     */
    public String getHurtName() {
      Object ref = hurtName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hurtName_ = s;
        return s;
      }
    }
    /**
     * <code>string hurtName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHurtNameBytes() {
      Object ref = hurtName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hurtName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hurtTimes_ != 0) {
        output.writeInt32(1, hurtTimes_);
      }
      if (!getHurtNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hurtName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hurtTimes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hurtTimes_);
      }
      if (!getHurtNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hurtName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Hurt)) {
        return super.equals(obj);
      }
      Hurt other = (Hurt) obj;

      boolean result = true;
      result = result && (getHurtTimes()
          == other.getHurtTimes());
      result = result && getHurtName()
          .equals(other.getHurtName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HURTTIMES_FIELD_NUMBER;
      hash = (53 * hash) + getHurtTimes();
      hash = (37 * hash) + HURTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHurtName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Hurt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Hurt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Hurt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Hurt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Hurt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Hurt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Hurt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Hurt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Hurt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Hurt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Hurt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Hurt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Hurt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Hurt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Hurt)
        HurtOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyDataInfo.internal_static_Hurt_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyDataInfo.internal_static_Hurt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Hurt.class, Builder.class);
      }

      // Construct using com.story.netty.protobufDemo2.MyDataInfo.Hurt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        hurtTimes_ = 0;

        hurtName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyDataInfo.internal_static_Hurt_descriptor;
      }

      @Override
      public Hurt getDefaultInstanceForType() {
        return Hurt.getDefaultInstance();
      }

      @Override
      public Hurt build() {
        Hurt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Hurt buildPartial() {
        Hurt result = new Hurt(this);
        result.hurtTimes_ = hurtTimes_;
        result.hurtName_ = hurtName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Hurt) {
          return mergeFrom((Hurt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Hurt other) {
        if (other == Hurt.getDefaultInstance()) return this;
        if (other.getHurtTimes() != 0) {
          setHurtTimes(other.getHurtTimes());
        }
        if (!other.getHurtName().isEmpty()) {
          hurtName_ = other.hurtName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Hurt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Hurt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int hurtTimes_ ;
      /**
       * <code>int32 hurtTimes = 1;</code>
       */
      public int getHurtTimes() {
        return hurtTimes_;
      }
      /**
       * <code>int32 hurtTimes = 1;</code>
       */
      public Builder setHurtTimes(int value) {
        
        hurtTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hurtTimes = 1;</code>
       */
      public Builder clearHurtTimes() {
        
        hurtTimes_ = 0;
        onChanged();
        return this;
      }

      private Object hurtName_ = "";
      /**
       * <code>string hurtName = 2;</code>
       */
      public String getHurtName() {
        Object ref = hurtName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          hurtName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string hurtName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHurtNameBytes() {
        Object ref = hurtName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hurtName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hurtName = 2;</code>
       */
      public Builder setHurtName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hurtName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hurtName = 2;</code>
       */
      public Builder clearHurtName() {
        
        hurtName_ = getDefaultInstance().getHurtName();
        onChanged();
        return this;
      }
      /**
       * <code>string hurtName = 2;</code>
       */
      public Builder setHurtNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hurtName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Hurt)
    }

    // @@protoc_insertion_point(class_scope:Hurt)
    private static final Hurt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Hurt();
    }

    public static Hurt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hurt>
        PARSER = new com.google.protobuf.AbstractParser<Hurt>() {
      @Override
      public Hurt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hurt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hurt> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Hurt> getParserForType() {
      return PARSER;
    }

    @Override
    public Hurt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Manager_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Manager_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Love_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Love_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hurt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hurt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nLove.proto\"\221\001\n\007Manager\022$\n\tdata_type\030\001 " +
      "\001(\0162\021.Manager.DataType\022\025\n\004love\030\002 \001(\0132\005.L" +
      "oveH\000\022\025\n\004hurt\030\003 \001(\0132\005.HurtH\000\"&\n\010DataType" +
      "\022\014\n\010LoveType\020\000\022\014\n\010HurtType\020\001B\n\n\010dataBody" +
      "\"+\n\004Love\022\021\n\tloveTimes\030\001 \001(\005\022\020\n\010loveName\030" +
      "\002 \001(\t\"+\n\004Hurt\022\021\n\thurtTimes\030\001 \001(\005\022\020\n\010hurt" +
      "Name\030\002 \001(\tB-\n\035com.story.netty.protobufDe" +
      "mo2B\nMyDataInfoH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Manager_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Manager_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Manager_descriptor,
        new String[] { "DataType", "Love", "Hurt", "DataBody", });
    internal_static_Love_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Love_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Love_descriptor,
        new String[] { "LoveTimes", "LoveName", });
    internal_static_Hurt_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Hurt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hurt_descriptor,
        new String[] { "HurtTimes", "HurtName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
